### ISSUE TITLE
Synchronize status message not updated after "Continue sync in background" button is shown.

### ISSUE THREAD

**Issue by dystania** [brianrak/satori-reader-mobile-beta#10]
**Describe the bug**
During the download, the screen stops refreshing on 429/1277 resources. It seems to stop as soon as the button appears that says "Continue sync in background" and stays that way as long as the button is on-screen though that's only observed behavior.

**To Reproduce**
1. Make sure your Device Settings under "Menu" -> "<User Name>" -> "Preferences" are set to "Download all content"
2. Go to "Menu" -> "Developer" -> "Delete All Resources" to allow you to replicate downloading all resources
3. Go to "Menu" -> UserName -> "Synchronize"
4. Wait for resources to download and for me it stopped on 429/1277 and then continue waiting for a period of time
5. Tap "Continue sync in background"
6. Go to "Menu" -> <User Name> -> "Synchronize"
7. You will see it restart the process of synchronizing and the downloaded files will have changed along with the remaining files but the numbers still do not update

**Expected behavior**
Resource download progress will continue to update on the screen to show the accurate amount of files downloaded.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 11.4

**Additional context**
The available capacity on my phone is 138.35 GB and I tested over 12 times over Wi-Fi and Cellular. I also tried only deleting 50% of the resources rather than all of them in the last couple of tests. I also varied the times in between.

**Comment by brianrak** [comment]
Hello, @dystania. Great bug! I found the underlying issue. We are indeed stopping our status message updates after it becomes possible to continue the sync in the background. Will fix in next build.

**Comment by brianrak** [comment]
Fixed in Build 0.906. Thank you!
