### ISSUE TITLE
Only able to force close the App with a Synchronize error

### ISSUE THREAD

**Issue by dystania** [brianrak/satori-reader-mobile-beta#11]
**Describe the bug**
I'm not 100% sure this is a bug but more of a logical design flaw. It appears the only way to leave the Synchronize View is if the download has succeeded enough that the button "Continue sync in background" appears, the Synchronize process has finished successfully, or the Synchronize process times out but still displays it finished successfully. When the Synchronize process has an error and reports it there isn't anything that can be done except for the User to close the App through iOS and then re-open the App forcing the system to attempt another Synchronize.

**To Reproduce**
1. First off it's incredibly hard to cause it to error.
2. Make sure your Device Settings under "Menu" -> "" -> "Preferences" are set to "Download all content"
3. Go to "Menu" -> "Developer" -> "Delete All Resources" to allow you to replicate downloading all resources
4. Go to "Menu" -> UserName -> "Synchronize"
5. Before the button "Continue sync in background" appears you need to switch the method of download like turning off Wi-Fi so it switches to Cellular

**Expected behavior**
I think a button to either cancel the download would be fine? Not sure what would be best to work with the backend process.

**Screenshots**
![img_0064](https://user-images.githubusercontent.com/13225902/41890351-c00b8c0c-78d4-11e8-8bba-43787008ba6c.jpg)
![img_0065](https://user-images.githubusercontent.com/13225902/41890352-c01a9ddc-78d4-11e8-8c61-030f7b8fba0e.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: 11.4

**Additional context**
It also appears that the App will say the Synchronize has finished successfully after timing out rather than saying that the process failed.

**Comment by brianrak** [comment]
Hello, @dystania. You are turning up some good ones! So turning off wi-fi midway through the sync allows the sync to fail?

The way this screen works is, there is indeed a minimum sync'd state that has to be met before the app can proceed into the main UI. We are trying to make that first part of the sync resilient enough to gracefully handle any issues that could occur, but it's probably not realistic to expect to handle them all. I think that, for cases in which we can't download enough (or verify already downloaded) to proceed for an unexpected reason, a Retry button makes sense. 

Will fix in next build.

**Comment by brianrak** [comment]
This is fixed in build 909. Now if an unexpected error prevents the sync from completing, you can retry or cancel (however, note that cancel is only available if a sync has previously completed).

Thank you for the bug!
