### ISSUE TITLE
Error when choosing Reviews from the main menu via the large (tablet) navigation: Encountered unexpected exception while rendering page content: The given key "REVIEW-FILTER" was not present in the dictionary.

### ISSUE THREAD

**Issue by dystania** [brianrak/satori-reader-mobile-beta#12]
**Describe the bug**
When clicking Review in the upper-left of the iPad it generates this error along with the error "Encountered unexpected exception while rendering page content: The given key "REVIEW-FILTER" was not present in the dictionary.Back to Account". Periodically you'll also get the error "An error was detected. Message: Script error. Line number: 0" as well.

**To Reproduce**
1. Tap "Review" in the upper-left of the screen
2. Tap the upper-left of the screen just above "Articles" as shown in the screenshot as a hidden link for satori://nav/account will be there to be tapped
3. You should arrive at the Account view and periodically you'll get the secondary error

**Expected behavior**
You should arrive at the Review view.

**Screenshots**
![img_0071](https://user-images.githubusercontent.com/13225902/41895494-caf1c11e-78e7-11e8-8efb-4ba3c1a59ded.jpg)
![img_0078](https://user-images.githubusercontent.com/13225902/41895495-cb032cd8-78e7-11e8-9f09-08c90ed45201.jpg)

**Smartphone (please complete the following information):**
 - Device: iPad 10.5
 - OS: 11.4

**Additional context**
The secondary error was originally my primary error until I determined how I was able to stay within the App and get to a screen that worked again.

**Comment by brianrak** [comment]
Hello, @dystania. Great bug. I'd like to drill in on your repro steps a bit. Are you saying that the message about the missing REVIEW-FILTER key appears just by virtue of navigating to the Review screen?

**Comment by catbadon** [comment]
I am also having this error. I can get to my reviews from the dashboard, but when I select the 'reviews' link from the top of the page the app freezes or gives that error.

**Comment by brianrak** [comment]
Hello, @catbadon. Thanks for the additional info.

Is anyone able to repro this on a phone, or are we seeing it only on tablets at this point? (Using these specific repro steps)

**Comment by dystania** [comment]
@brianrak The Review view shows up fine on my phone. The steps are slightly different since I

1. Tap Menu icon
2. Tap Review
3. Review view shows up

It shows up fine for me though on the phone. I also verified the tablet reproduces the error in both landscape and portrait mode as I hadn't tested if there was a difference earlier.

Model: iPhone X
OS: 11.4

**Comment by brianrak** [comment]
@dystania Gotcha. Thanks for the additional info. I have found and fixed the underlying issue and it should work properly in the next build. Thank you!

**Comment by brianrak** [comment]
Fixed in Build 0.906. Thank you, everyone!
