### ISSUE TITLE
Developer options missing in tablet navigation

### ISSUE THREAD

**Issue by dystania** [brianrak/satori-reader-mobile-beta#13]
Not really a question or discussion but I realized now why it was questioned how I was removing the resources and forcing the synchronization process without leaving the App.  I've included the two screenshots of my two test devices so that you can see the differences.

I had assumed incorrectly that the "Developer" options were left in the App for our testing purposes but after viewing the iPad I'm not so sure. It has helped with my testing the synchronization process. Hope this clears up how I was initiating the Synchronization process and removing the resources to test out the refresh of the Synchronization view.

Model: iPhone X
OS: 11.4

![img_0066](https://user-images.githubusercontent.com/13225902/41895994-1940e51a-78e9-11e8-8645-d4053ccf2d9f.jpg)

Model: iPad 10.5
OS: 11.4

![img_0092](https://user-images.githubusercontent.com/13225902/41896009-20b8b3ea-78e9-11e8-8653-c0b2630bf134.jpg)

**Comment by brianrak** [comment]
Hello, @dystania. Thanks for the question! Yes, those options were indeed left in to help with testing. It looks like we put them into the mobile view of the nav, but not the larger view. (I guess that's sort of a bug -- I'll see about adding them to the larger view too.)

Thanks for explaining more about the other bug. I will take a look at it and reply more there.

**Comment by brianrak** [comment]
Will fix in next update, ETA later this week.

**Comment by brianrak** [comment]
Fixed in Build 0.906. Thank you!
