### ISSUE TITLE
Users who only sign in via Facebook cannot sign into the app

### ISSUE THREAD

**Issue by guidomamone** [brianrak/satori-reader-mobile-beta#17]
Hello!

Ive always logged in with Facebook. Since in the app i cannot do that yet, I need to type my user and password. Buuuut, they are not the same Facebook uses, so I can actually log in. Am I omitting something? Sorry if question is not the brightest!

Thank u!

**Comment by brianrak** [comment]
Hello @guidomamone,

That's great feedback. Sorry for the confusion. Facebook login is not yet supported within the mobile apps. So you'll need to add a regular email address + password login. You can add this to your existing Satori Reader account by doing the following:

1. Log into Satori Reader as usual.
2. Go to your Account page (under your name in the main menu).
3. Under "Email Address," set an address if there is not already one there.
4. Confirm the address by clicking the link in the confirmation email.
5. Back on the Account screen, under "Change Password," set a password.

You can now log in using either your Facebook account or the email address + password combination you created. Please give this a try and let me know if you have any trouble!

We'll work on a better solution to this.

**Comment by guidomamone** [comment]
perfect Brian! Ive been able to do it (although I had to reset my password with the "forgot my password option" because Satori didnt recoignise me any Current Password).
ty a lot!

**Comment by brianrak** [comment]
@guidomamone Great! I'm glad to hear you're able to log in. Clearly, this will affect other Facebook users too. Thanks for logging this!

**Comment by brianrak** [comment]
Fixed in 0.913.
