### ISSUE TITLE
Cannot access (why?) help webpage on words that are normally represented in hiragana

### ISSUE THREAD

**Issue by catbadon** [brianrak/satori-reader-mobile-beta#18]
When I click on the (why?) in the dictionary entry box for a word that says "this word often appears in kana", it cannot load the help page. Error says "The webpage at file://help#kanji-kana-representation could not be loaded because: net::ERR_FILE_NOT_FOUND

**To Reproduce**
1. Go to an article with a word that is usually in hiragana. 
2. Click on the vocab word to open the dictionary entry box. 
3. Click on the (why?) link. 

**Expected behavior**
Loads to the webpage explaining hiragana representation.

**Screenshots**
![screenshot_20180719-131516](https://user-images.githubusercontent.com/40582750/42962670-c17a647e-8b57-11e8-91cd-a4f13ae2f0ee.png)
![screenshot_20180719-131705](https://user-images.githubusercontent.com/40582750/42962671-c1b39a0a-8b57-11e8-949a-f73f1fb76210.png)
![screenshot_20180719-131733](https://user-images.githubusercontent.com/40582750/42962672-c1c99af8-8b57-11e8-87b2-62aee967af5e.png)

**Tablet:**
 - Device: Galaxy Tab A
 - OS: Android 7.0

I found these words in the following articles: 
Secret-Wanderer-"こと”
Kona's Big Adventure- Tingling with excitement- "ひも"

**Comment by catbadon** [comment]
I also recently got a new smartphone, and I get the same error on it.
Smartphone:
Device: moto G6
OS: Android 8.0.0

**Comment by brianrak** [comment]
Good catch!

**Comment by brianrak** [comment]
This bug is fixed in Build 0.912. Thank you!
