### ISSUE TITLE
Review section shows incorrect number of review or no reviews

### ISSUE THREAD

**Issue by catbadon** [brianrak/satori-reader-mobile-beta#23]
**Describe the bug**
The app shows that I have 0 review cards on my smartphone, and only 14 review cards on my tablet. I actually have over 700, and the website still shows that I have these to review. I got a little behind.

**To Reproduce**
1. Go to Reviews.
2. Page says ' You currently have no cards.', even though I do.
3. Clicking on review hard cards or review all cards still says I have no cards to review.

**Expected behavior**
Page shows number of cards to review, and links to SRS reviews.

**Screenshots**
On the tablet.
![screenshot_20180727-150037](https://user-images.githubusercontent.com/40582750/43344616-094193e6-91b0-11e8-8f76-08b4d56f2329.png)

On the smartphone.
![screenshot_20180727-145850](https://user-images.githubusercontent.com/40582750/43344626-10d05674-91b0-11e8-96cf-f426bd7c9bae.png)

Website on the computer, with correct number of reviews.
![screen shot 2018-07-27 at 3 06 19 pm](https://user-images.githubusercontent.com/40582750/43344650-20b26cb2-91b0-11e8-94a1-f684302e4ce7.png)

**Smartphone:**
Device: Moto G6
OS: Android 8.0.0

**Tablet**
Device: Galaxy Tab A
OS: Android 7.0

**Additional context**
The 14 reviews available on my tablet are cards that I added two days ago.

**Comment by brianrak** [comment]
Hello, @catbadon. Thanks for the report! Quick question -- when you installed this build, did you completely uninstall the previous one or upgrade in place? For this build only, it's important to fully uninstall the previous build and install the new one afresh. We made some major modifications to how user review cards are stored under the hood, which will lead to dramatically faster synchronization in certain scenarios, but the changes weren't totally backward compatible with the previous beta builds. 

Please uninstall, re-install, and re-sync and let me know if you still have this issue. Thank you!

**Comment by catbadon** [comment]
I had upgraded in place. I uninstalled and reinstalled the app, and that fixed the problem. Thank you!

**Comment by brianrak** [comment]
Great! Glad to hear things are working properly now.
