### ISSUE TITLE
Login screen doesn't prompt for email address. (What's my  username?)

### ISSUE THREAD

**Issue by bengaskin** [brianrak/satori-reader-mobile-beta#24]
**Description**
The app asks for a username rather than an email address
(unlike the website which uses both terms:
"Sign in with username and password
Email:______"
Password:______")

**To Reproduce**
Sign out (if already logged on) and Sign in .

**Expected behavior**
If my username is my email address, I expect to see the word "email", not (only) the word "username"
Users may be unaware of their username or forget that their username _is_ their email address
(I don't know if username = email address is true for all users, but in the website version the username field is labelled "Email").  

**Smartphone (please complete the following information):**
Android
Samsung Galaxy S6 Edge
SC04G
OS Lollipop 5.0.2

**Additional context**
I find the website easier to use in this regard.
I have a note of my password but I don't keep a note of my username, because the website asks me for my email address... which I remember implicitly without thinking of as a username.

**Comment by brianrak** [comment]
This bug is fixed in Build 0.912. Thank you!
