### ISSUE TITLE
Sort by "unread" randomizes article list (mobile +website  bug)

### ISSUE THREAD

**Issue by bengaskin** [brianrak/satori-reader-mobile-beta#25]
**Describe the bug**
A bug in the app _and_ the website.
Given a set of articles with same unread status (eg. all articles are read),
clicking on the unread link to sort read-->unread or unread-->read sorts the articles randomly.

This is not a bug in core functionality but an undesired side-effect.

**To Reproduce**
From articles screen when logged in to app, 
1.Click into series (eg. Akiko's American Foreign Exchange)
(pre-requisite multiple articles are marked as completed and multiple are marked as unread)
2.Click on (Sort by:) Unread
3.Click on (Sort by:) Unread again. 
4.Click on (Sort by:) Unread again. 

**Expected behavior**
Expected behaviour for step 2: some kind of sort.
Expected behaviour for step 3: some kind of sort.  Likely a reversal of step 2. So may not look identical
Expected behaviour for step 4: some kind of sort "reversing the reversal" back to the same as at step 2.

However,  the article list seems to be somewhat randomized from step 2 to step 3 to step 4.

**Screenshots**
Attached. Multiple screenshots per step. For these screenshots each time I took a screenshot and then scrolled down a bit and took a new screenshot to show the first article listed.

**Smartphone (please complete the following information):**
Android
Galaxy S6 Edge
specific hardware model SC04G
OS Lollipop 5.0.2.

**Additional context**
For my examples, I used Akiko no Nikki.  All my Easy articles are completed and some Hard ones. Many of my Hard articles are Unread.

![screenshot_2018-07-31-12-53-21](https://user-images.githubusercontent.com/2171875/43437061-24e64410-94c2-11e8-99c7-84c0419a8617.png)
![screenshot_2018-07-31-12-53-26](https://user-images.githubusercontent.com/2171875/43437062-25113fee-94c2-11e8-85bf-3418f1c59530.png)
![screenshot_2018-07-31-12-53-29](https://user-images.githubusercontent.com/2171875/43437063-25397bda-94c2-11e8-82d2-a9e1a16034b9.png)
![screenshot_2018-07-31-12-53-36](https://user-images.githubusercontent.com/2171875/43437064-2566c400-94c2-11e8-98b8-0d6c6b754f25.png)
![screenshot_2018-07-31-12-53-39](https://user-images.githubusercontent.com/2171875/43437066-258f7684-94c2-11e8-8cd5-6bff89f69a0d.png)
![screenshot_2018-07-31-12-53-44](https://user-images.githubusercontent.com/2171875/43437067-25b89208-94c2-11e8-850e-f4a5a8859810.png)
![screenshot_2018-07-31-12-53-48](https://user-images.githubusercontent.com/2171875/43437068-25e1b606-94c2-11e8-9f4d-b1c7f032cc94.png)
![screenshot_2018-07-31-12-53-53](https://user-images.githubusercontent.com/2171875/43437069-260b8e54-94c2-11e8-85d7-d14973412765.png)
![screenshot_2018-07-31-12-53-57](https://user-images.githubusercontent.com/2171875/43437070-2638c6d0-94c2-11e8-8362-9c9a773f3133.png)
![screenshot_2018-07-31-12-54-01](https://user-images.githubusercontent.com/2171875/43437071-266423e8-94c2-11e8-9776-10e6c8e66481.png)
![screenshot_2018-07-31-12-54-04](https://user-images.githubusercontent.com/2171875/43437072-269a2452-94c2-11e8-94fc-08f38c552828.png)

**Comment by brianrak** [comment]
Fixed in 0.913.
