### ISSUE TITLE
"Reveal in Full Original Context" undesirably refreshes review session

### ISSUE THREAD

**Issue by bengaskin** [brianrak/satori-reader-mobile-beta#26]
From an in-progress review session, clicking on "reveal in full original context" resets the review session.
ie. pressing the back button after viewing the original context leads to:
"Initializing", "Creating a customizing review for you." review card 1 of 20 instead of returning to the exact review session that was in progress, card x/y

**To Reproduce**
Hamburger menu > Review >any review link (eg. review all your cards) > reveal in full original context > smartphone physical back button.

**Expected behavior**
If I'm in a review session and I go to reveal in full context, I consider this a detour.  So when I click the back button, I expect to be back at that same review card.

**Screenshots**

**Smartphone (please complete the following information):**
 - OS: [e.g. iOS 8.1]

**Additional context**

I can see how this could be seen as an irrelevance, but I still think it's a big deal in terms of expected persistent state. It's a bit jarring to have the landscape shift around you.

Use cases:

Consider the case when there are multiple contexts that I want to see in full to best learn a particular vocabulary item or grammar point.

I would lose my place, and not be able to click to a second context.

More often, it's just wanting the extra reassurance... I saw the full context, now I can read it again and check I understand it now before I move on to the next card.

Also, there's a feeling of lack of flow if you're at card 18/20, then being told you are now at card1/20. (even though the bigger set of cards is still being moved through).

**Comment by brianrak** [comment]
Good call! Fix coming in the next build.

**Comment by brianrak** [comment]
This bug is fixed in Build 0.912. Thank you!
