### ISSUE TITLE
Unable to select and copy text of article or notes

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#28]
In**Describe the bug**
When using a web browser on iPad, I can select (long press) and copy text in an article or note. I use this frequently to copy and paste text into my dictionary app. Using the mobile app, I am unable to select text.

**To Reproduce**
Go to main menu, click on Articles, open an article. 
Long press on any text. Nothing happens. Remove finger and text has blue underline. Short tap produces dict entry popup.
Same issue with text in Review.

**Expected behavior**
Long press should produce a popup magnified view above the line enabling you to slide around and choose selection location. Release should leave a selection range with start and end drag handles and a black menu popup list: Copy, Look Up, Learn ..., Share ...

**Screenshots**

**Smartphone (please complete the following information):**
iPad mini 4
iOS 11.4.1

**Additional context**
Unless this is intentional, it is a fatal omission. Does not support my preferred style of study.

Update. Noticed can select text in Discussion. Still not in articles.

Richard H

**Comment by brianrak** [comment]
Hello, @issekinichou. Thank you for the bug report. Investigating now...

**Comment by bengaskin** [comment]
FWIW I just came here to report the same bug / feature request and saw it was already logged here. Could be a big deal for language learners, since we often copy paste text to Google translate, Kanji dictionaries etc.

**Comment by brianrak** [comment]
Thank you for the vote, @bengaskin. I'll look into this and we'll see what we can do.

**Comment by brianrak** [comment]
Fixed in 0.914.
