### ISSUE TITLE
No back (or forward) buttons for navigation

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#30]
**Describe the bug**
In my web browser, I can use back and forward arrows. Mobile app does not have these browser functions. This makes navigation cumbersome. For example in Discussion, after selecting Feedback, I might want to look at Bugs or Questions. Navigation takes too many steps.

**To Reproduce**
Dashboard, MyStats, Join Discussion Now, Feedback
After reading Feedback, to navigate to another discussion topic, the only navigation option seems to be Menu, Dashboard, MyStats, Join Discussion Now ... !

**Expected behavior**
I expect to see a back button that takes me back one step to the four discussion topics. Instead it takes 4 or 5 steps via menu navigation.
An example of an app with back/forward buttons is The free Dictionary by Farlex.
A forward button is also useful.

**Smartphone (please complete the following information):**
 iPad mini 4
iOS 11.4.1

**Additional context**
Not a bug, it does work. Omission of familiar browser features.

Richard H

**Comment by brianrak** [comment]
I can see how that would be cumbersome getting between the Dashboard > Discussion pages. Android devices have a hardware back button, but iOS devices don't, and I'm a little hesitant to give up space. Perhaps we could make the swipe gesture into a Back button. I'll investigate.

**Comment by brianrak** [comment]
Fixed in 1.0.5.
