### ISSUE TITLE
No way to sync Kanshudo 

### ISSUE THREAD

**Issue by Jdzspace** [brianrak/satori-reader-mobile-beta#31]
On the main site you could import known kanji from kanshudo or wani kani, or select kanji from genki textbook etc. But I'm not seeing those options on the app. Is that to be added later or only through the main site?

**Comment by brianrak** [comment]
Indeed, you are correct! So sorry about that. Will fix in the next build.

**Comment by brianrak** [comment]
Fixed in 0.913.
