### ISSUE TITLE
Pages are refreshed when changing screen orientation

### ISSUE THREAD

**Issue by mrlordbender** [brianrak/satori-reader-mobile-beta#32]
**Describe the bug**
In any page (but the loading page) changing screen orientation on the mobile causes the page to reload and reset the position to the top.
This is especially annoying in the following cases:

- when listening to an article since audio is stopped and reset to the beginning.

- when making reviews, since it refresh and generates a new set of cards

**To Reproduce**
Simply rotate the screen (with screen layout rotation enabled of course) while doing  a review or reading an article (with or without listening to it)

**Expected behavior**
The web application behaves well in this case: it simply adapts the layout without interrupting the play-though and resetting the position of the page to the top. (it doesn't even refresh the page actually).

**Smartphone**
Galaxy S7 Edge - Android O

Thanks!
V

**Comment by issekinichou** [comment]
I don't see this behavior on iOS.
Article text moves a bit from landscape to portrait but not back to the start. Middle or end rotates to about the same position.
Sound continues without interruption

iOS11.4.1, iPad mini 4.

**Comment by brianrak** [comment]
Hello, @mrlordbender. Thank you! 

I am confirming that this happens on Android, and not on iOS, currently. We're looking into fixes now.

**Comment by brianrak** [comment]
Fixed in 0.913.
