### ISSUE TITLE
Article status changes do not show up in dashboard

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#34]
**Describe the bug**
Changes to articles status (unread, started, completed) do not show up correctly in Dashboard. May be a bug on the website too.

**To Reproduce**
Open an article (trialled Restaurants MacD)
Changed from completed to started
Navigate to Dashboard
Does not show up under Started
Tried Sync, still does not show.

Another article (cancelling reservation)
Changed completed to unread.
++ App dashboard do not offer See All with filtering All, started, completed which the web site does! See separate bug report
Looking on website, article (cancelling reservation) is Status: Unspecified

Another article (peanut allergy. I sorted restaurants by difficulty)
On website, changed completed to unread.
Website dashboard, All: article not at top. Looked carefully, could not see the image anywhere in the list. Back to article, confirmed Unread. In app (open simultaneously), synchronize, returned to article, status shows here as Unread. 

Another article (hold garlic)
In app, changed completed to started.
Dashboard does not show, synchronize, not change.
View website. Started does not have it. All shows it as Started at top of list. Completed shows 3 yellow statuses at the top of the list. Garlic started, Cancelling unspecified, McD started

**Expected behavior**
I would expect Started, My Recent Articles to show articles with status started.
I would expect sort by Completed to have completed articles at the top not started ones.
On website, status: Unspecified sounds like an error: should be unread.

**Screenshots**

**Smartphone (please complete the following information):**
 - iPad mini 4
iOS 11.4.1

**Additional context**
I could fiddle around more, but I'd prefer you guys to take a look first.

**Comment by brianrak** [comment]
Hello, @issekinichou. Nice catch! I am able to reproduce this on the website. Investigating now.

**Comment by issekinichou** [comment]
I did a bit more testing in 0.913 and on the website.
Changes made on website alone are ok, except for issue with status: unspecified. Changing started or completed article to unread (and bookmark) shows unspecified if you look under bookmarked articles.

Making changes in the app.
Changing status to unread shows as unspecified in dashboard started. This is also visible on website dashboard started.
Changing status to completed shows as green completed in dashboard started. (Note the text reads: Below are articles you've started but haven't yet marked as completed.)

That's all from me on this issue until something changes.

**Comment by brianrak** [comment]
Fixed in 0.915.
