### ISSUE TITLE
No audio controls in portrait mode when viewing original article from review link

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#37]
**Describe the bug**
Linking to the original article from a review card, the overlay has no audio controls in portrait mode. You can play individual sentences, but you cannot pause them. You have to rotate to landscape to get the audio controls.

**To Reproduce**
Review, follow link, portrait mode

**Expected behavior**
In the app, reading an article from Articles in portrait mode, you get audio in the orange header as well as the gear wheel settings.

**Smartphone (please complete the following information):**
 iPad mini 4
iOS 11.4.1

**Additional context**
Another related issue but less important issue is that you cannot see the difficulty level for articles with multiple versions (eg Akiko). Rotating invokes the audio bar but not the sidebar.
I previously mentioned this in website discussion and I think you noted it for consideration. Maybe adding level in the title.

**Comment by brianrak** [comment]
Under investigation.

**Comment by issekinichou** [comment]
On my small screen iPod, there are no audio controls in either view. Only the play buttons for individual sentences. No pause, no continuous play. The view does rotate into landscape, but the grey floating slider at the bottom is absent.
The normal view of articles has controls in the orange header for both portrait and landscape.

iPod touch 6
iOS 11.4.1

**Comment by brianrak** [comment]
Fixed in 0.914.
