### ISSUE TITLE
Scrolling notes is improved!

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#38]
Nice. In both articles and review article overlays, if you open a long note, you can scroll up and down with no problem. The note is solid unless you tap close X or tap another note underline.
I hope this behavior can be implemented on website. Thanks.

**Comment by brianrak** [comment]
Hello, @issekinichou. Great! One question for you: When you say that it doesn't work as well on the website, do you mean from within a browser on a mobile device, or on a PC/Mac?

**Comment by issekinichou** [comment]
I meant browser (safari) on iPad. It's is often ok in landscape mode, but in portrait mode, scrolling a note usually causes it to vanish. Long notes are usually unreadable in portrait mode. Landscape mode loses them if your finger is within the note, but may work if your finger is in the sidebar outside the note (which is impossible in portrait mode).

Desktop is a laptop attached to a big screen and notes scroll fine in safari and in maxthon. I just tried for first time on the built-in screen. Same, no problems. But I usually read articles on iPad.

**Comment by brianrak** [comment]
We figured out the underlying cause of this while resolving #51. The popups stay popped up and properly close when tapping outside now. This change is also going to the website shortly, so you should notice improvement all around.
