### ISSUE TITLE
No Export in app

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#39]
In Review, there is no export function in the app. Is this likely to be added in future or is it technically difficult?

**Comment by brianrak** [comment]
An implementation in which you can create and retrieve exports from within the app will probably have to be postponed until after launch. However, we could include a link to the website so that people are aware that the functionality exists. Will add to the next build.

**Comment by brianrak** [comment]
Link added in 0.914.
