### ISSUE TITLE
Welcome Tour under Preferences causes a freeze

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#40]
**Describe the bug*
Starting the welcome tour leads to a blank white unresponsive page. 
**To Reproduce**
User name, Preferences, Welcome Tour
Restart Welcome Tour
Success (green box) Head to the articles page ...
Tapping the link leads to a blank page.
Double tap home button and quit app to escape

Logged on website and it opened in tour mode.
Cancelled tour.

Repeate freeze and quit.
Relaunch app works normally.
Log onto website. It is in tour mode. 

**Expected behavior**
Expected app to show tour mode like website.

**Smartphone (please complete the following information):**
iPad mini 4
iOS 11.4.1

**Additional context**
I think this is different from the video tour known issue #5.
Is this welcome tour mode unimplemented too? warn testeers to avoid it.

**Comment by brianrak** [comment]
Nice catch. Investigating now. We are not planning on showing the Welcome tour on mobile because takes up a lot of screen real estate and so feels a little clunky. The video tour will provide the same information in an easier-to-digest format.

**Comment by brianrak** [comment]
Fixed in 0.913.
