### ISSUE TITLE
How about listing positive things that we have checked and work fine?

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#41]
Would it help if we list things that we have checked and found do work?
The absence of a bug report might mean that no one has checked.
Also, you, Brian, could list things that you would like us to check.
It might be that none of the current testers performs a certain action (eg logging in via Facebook on iOS)

For example, I have found that synchronize works fine in both directions. On opening the app, it is updated with any changes made on the server, and on closing the app, the server is updated. And changes made on the website can be seen in the open app if you tap synchronize under user name, though it exits the current page and goes through the launch sequence and reopens on the articles page. I sometimes log into the website simultaneously in a browser. In particular, that is a useful (hopefully temporary) work-around for not being able to copy text in articles and review.

**Comment by brianrak** [comment]
Hello, @issekinichou. Thanks for the question!

I think that listing each thing that seems to be working properly would overwhelm us. Let's keep the focus on issues. If there are specific scenarios we'd like tested, we'll let you know. We are also performing our own internal testing of things we think might get missed by the general shotgun approach.

Glad to hear that sync is working properly. Just to let you know, changes you make in the app are sent to the server very quickly (within seconds), whereas changes made on the server are picked up by the app less frequently (this prevents the app from having to poll for updates all the time). As you have discovered, you can force a sync to pick up server changes by going to the Synchronize screen. But even if you don't those changes will come in via a background sync (currently the app polls at 5 minute  intervals).

**Comment by issekinichou** [comment]
That's fine, quite understandable.
