### ISSUE TITLE
0.913 Discussion, Disqus worse than 0.912

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#43]
**Describe the bug**
In 0.913, Discussion (Discussion page or article Discussion) opens browser app to display Disqus. I can read the discussion, but I cannot see my notifications (gray counter, user name is Login) and cannot write comments (not logged in). Note I use a local (Satori) discussion account.

**To Reproduce**
Open article, Discussion or
Dashboard, Join Discussion, choose any topic.

**Expected behavior**
In 0.912, the discussion opened locally in the app, showed "you are using a local account', and I could see my user name, notifications counter and make comments. That was fine. Why change it? Is it better for non-local accounts? 0.913 implementation is unusable.

**Smartphone (please complete the following information):**
 iPad mini 4
iOS 11.4.1

**Additional context**
Disqus local account on satori.

I re-installed 0.912 to confirm my memory of the behavior.
Have now re-updated to 0.913 to continue testing that.

**Comment by brianrak** [comment]
Hello, @issekinichou. We didn't actually change anything related to the Discussion between these two builds. I'm not sure why you saw this behavior. But this does highlight a pitfall on relying on Disqus. We're actively looking at whether we can switch to a very basic discussion system of our own design prior to launching this app. Please stay tuned.

**Comment by brianrak** [comment]
Found and fixed this is 0.915.
