### ISSUE TITLE
Disqus sorting order does not match setting on website/server

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#44]
**Describe the bug**
I raised this issue in #29 point 4 concerning 0.912. Brian asked me to raise it as a separate bug.
In 0.912, after installing and launching the app and later opening a discussion page for the first time, I noticed the sort was Best rather than my usual Newest, which I could see on the website by logging in in a browser. Later, I found it had changed in the app to Newest, so the issue might be slow sync.
0.913 changes the behavior of Disqus presentation and makes it hard to test. The presentation probably needs further changing (see issue 43), so I would prefer to save my testing for later.

I tried changing the website settings to Oldest and Best, but it did not sync even with force Synchronize. 

This is a fairly trivial issue that I just mentioned in passing as a noticeable difference. It's not hard to change manually. 

**To Reproduce**

**Expected behavior**
Expected sort order in app to be Newest, same as website.

**Smartphone (please complete the following information):**
iPad mini 4
iOS 11.4.1

**Additional context**

**Comment by brianrak** [comment]
I'm marking this `wontfix` not because I don't think it's a good issue, but because we are working on a replacement for Disqus that should work a lot better for our needs.
