### ISSUE TITLE
Stuck at welcome screen while synchronizing with server (Android 6.0.1)

### ISSUE THREAD

**Issue by amethystlexi** [brianrak/satori-reader-mobile-beta#46]
Bug Description:
App stays forever on the "Welcome back [user]" screen, at the message "Synhronizing with server. Applying deltas..."

Reproducing the bug:
- The bug appears every time I try to log in.
- The problem appears with all three options of syncing content (Cloud, Download Favorites, Download Everything) _(Although I will admit I have no way to make sure the app is actually applying the change in this setting)_
- The app doesn't stay stuck at the welcome screen if I open the app without an internet connection (but stays stuck if I just close the internet connection without closing and re-opening the app). Without a connection, the synchronizing message is quickly replaced by a "Could not sync article data" message, with the options to sign out or retry. However, if I re-connect to the Internet and retry (or sign out and back in again), I face the problem again.

Expected behavior:
The app should eventually move past the "welcome back" screen.

Smartphone:
 - Device: Sony Xperia Z2 (model D6503)
 - OS: Android 6.0.1

Additional context:
- Due to the nature of this bug, I'm assuming this is related to my phone having an older Android version.

**Comment by brianrak** [comment]
Hello @amethystlexi. Thanks for the issue report! I'm wondering if perhaps the app was indeed synchronizing your user data but just taking a long time with it. Do you have a lot of review cards?

**Comment by amethystlexi** [comment]
Thank you for replying! :)

I do have a lot of cards, but on one occasion I left the app running for close to 20 minutes and it still remained there.

However, I will try again today to leave it running for as long as possible, to check if you're right, and I'll comment here again with an update.

**Comment by brianrak** [comment]
Hello, @amethystlexi. Thanks for the follow-up. I'm glad that things are working for you now, but this is certainly something we will need to look into. I actually think that having 4000 cards is not that rare. I'm going to try to reproduce this issue and see if I can figure out how to make the sync work faster in this case, or at least provide better feedback on what is going on.

**Comment by brianrak** [comment]
Performance of large full syncs massively improved in 0.914. Further improvements under consideration.
