### ISSUE TITLE
Unparsed HTML showing for some articles' title in Dashboard screen

### ISSUE THREAD

**Issue by labsdul** [brianrak/satori-reader-mobile-beta#47]
**Describe the bug**
Using the Dashboard screen on the app, one of the articles (*Streetside Interviews - Shoushika-Mondai: Tomomi, Part 2*) has a title showing unparsed HTML (`<em>...</em>`). The other screens I tried (browsing the actual article or having it listed in *Streetside Interviews*) don't seem to have the problem. On a desktop browser, the title is fine everywhere. I am not sure if this is related to the mobile app or the articles metadata, or something else though. This is definitely not anything serious, but I have yet to encounter some bona fide bug. 

**To Reproduce**
1. If it is not already on your dashboard, start the article named *Streetside Interviews - Shoushika-Mondai: Tomomi, Part 2* so it can be listed on the Dashboard screen.
2. Go to the Dashboard screen.
3. Scroll down until the article *Streetside Interviews - Shoushika-Mondai: Tomomi, Part 2* is shown.

**Expected behavior**
Not showing unparsed HTML in the title of an article (nor anywhere else).

**Screenshots**
https://imgur.com/a/H97R3Vg
First screenshot is desktop, second is mobile. The problem is on the last visible article.

**Smartphone**
 - Device: Xiaomi Redmi 4X
 - OS: Android 7.1.2

**Additional context**
N/A

**Unrelated side note**
Not a bug or even a request, but at the moment, the series' title is not showing on the app, unlike the browser. I can understand wanting to limit the information to the essential stuff due to being limited to a tiny screen, but I would rather have larger cards with the series title in it. But I am far from being a frequent user, so my opinion isn't worth much - just thought I would mention it.

**Comment by issekinichou** [comment]
I tried this on iOS and saw it too.
iPad mini 4, iOS 11.4.1
Articles, open Tomomi 2. Mine is completed so I bookmarked it. Did not change article status.
Dashboard Started does not show it.
Under Bookmarked, it's top of the list August 16.
<em>Shoushika Mondai</em> Tomomi, Part 2.
Tapped name to open article
Changed status to Started
Dashboard Started did NOT show it! 
Bookmarked showed it as yellow Started
Tapped article, confirmed status
Dashboard
This time Started has it top of the list. <em>Shoushika Mondai</em> Tomomi, Part 2
Tapped article
Changed status to completed
Dashboard Started has it in green Completed top of the list  <em>Shoushika Mondai</em> Tomomi, Part 2
Ditto bookmarked.

**Comment by brianrak** [comment]
Under investigation.

**Comment by issekinichou** [comment]
After you fixed #49, this week's recent releases showed up.
The second on the list had em tags. I think it was em open Shiawase to wa em close

**Comment by brianrak** [comment]
Fixed in 0.914.
