### ISSUE TITLE
App goes to splash screen and freezes when used simultaneously with website.

### ISSUE THREAD

**Issue by bengaskin** [brianrak/satori-reader-mobile-beta#50]
App goes to splash screen and freezes when used simultaneously with website.

Steps to reproduce
(maybe not all of these steps are required exactly, but it was the most reproduce-able I could make it).

Starting from
-Signed in to Satori Reader on website on Android device (Android Chronme)
-Signed in to Satori Reader on app (Android)

In App: 
Review (to start a review session)> Reveal in full context (from any review card).
(Now take a note of the article name that's related to the review card)

On website:
Navigate to 
Articles > click on same article name to open
click on any word/phrase to bring up dictionary entry pop-up

Return to app
(ie. on my phone I click on the soft-touch hardware  button to show running apps,
then choose Satori Reader).

App is now full screen orange splash screen with only words Satori Reader and logo.
I have to force-kill the app and open it again.

I can reproduce this exactly like this, above instructions (using android app and android browser at same time).
I couldn't reproduce it by using the Satori website on my desktop PC at the same time as using the android app.

I don't know if this is because of any same-state on android (IP address etc) or because of of the way android has one app in focus at a time and I took focus away from the app and returned focus.

**Comment by issekinichou** [comment]
Just to confirm, this does not seem to be an issue on iOS.

On returning to the app, it opens on the same context article page. The popup is open, but sometimes quickly disappears and sometimes remains. I have not discovered any cause for the difference, but it seems unimportant. 
When switching to the web browser (safari), the popup always quickly disappears.

I frequently have both app and browser logged in simultaneously. No problems.

**Comment by brianrak** [comment]
Hello, @bengaskin. Thank you for the bug report!

Does this occur for you when you switch to some other app besides Satori Reader and then switch back to it?

**Comment by bengaskin** [comment]
I had a new issue very recently (fwiw it was the app completely freezing on startup every time), and I uninstalled and reinstalled and don't have the same issue.

Might as well close this one off as a freak one off occurrence, some update didn't take correctly or whatever.

What's the protocol, I can close this myself? I'll go ahead, let me know if it's not the best way for future reference.

**Comment by brianrak** [comment]
Okay, sounds good. I think you might be right. It could also be related to a sync issue we have just fixed in the most recent update as well. Please let us know if you see this in the future. Thank you!
