### ISSUE TITLE
Tapping a blank spot in the article does not close popup on iOS.

### ISSUE THREAD

**Issue by brianrak** [brianrak/satori-reader-mobile-beta#51]
**Describe the bug**
Within an article, if you tap a word to bring up a popup, on the website and on Android, you are able to dismiss the popup by tapping some other part of the screen. This does not work properly on iOS.

**To Reproduce**
1. Browse to any article.
2. Tap a word to bring up a popup.
3. Tap a blank part of the article.

**Expected behavior**
The popup is dismissed.

**Smartphone (please complete the following information):**
 - Device: iPhone 6
 - OS: iOS 11.4

**Comment by issekinichou** [comment]
This seems related to issue 38. Scrolling notes is improved.
If you can keep the notes stable and also provide blank tap dismissal, that's great.
If there is a conflict on iOS, then my preference is for stable note scrolling.

**Comment by brianrak** [comment]
Fixed in 0.914.
