### ISSUE TITLE
Difficulty level radio buttons don't work in landscape article view

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#52]
**Describe the bug**
In landscape view, the radio buttons for difficulty level do not work.

**To Reproduce**
Open article that has different level versions.
Any article? I tested four. Akiko snow lake 17, 18, news starbucks, sakura 1.
Kanji, furagana, and spaces radio buttons all work as expected.
Difficulty level buttons: nothing happens.
In portrait mode, you can switch level via the gear wheel.
In landscape mode, level is different but you still cannot change it.

**Expected behavior**
Tapping the level radio button should change version and the orange dot.
Works on website.

**Smartphone (please complete the following information):**
iPad mini 4
iOS 11.4.1

**Comment by brianrak** [comment]
Fixed in 0.914.
