### ISSUE TITLE
Announcement: Build 0.914 is now available.

### ISSUE THREAD

**Issue by brianrak** [brianrak/satori-reader-mobile-beta#54]
This build has lots of bug fixes including:

- Tapping blank space does not close popup.
- Synchronizing 4000 cards takes a very long time to complete.
- No audio controls when viewing article in modal window launched from review screen.
- Unable to copy text.

Thank you for your continued help!

**Comment by issekinichou** [comment]
Thanks. Items 3 and 4 above represent a huge improvement.
Did my first daily review using the app today where I could copy and paste into my dictionary app.

**Comment by brianrak** [comment]
Great -- Glad to hear it!
