### ISSUE TITLE
Question: can mobile apps (in general) detect presence or absence of internet connection?

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#57]
Can mobile apps (in general, not just satori) detect the presence or absence of internet connection?
Can't it run a communication test with the server?

If yes, then the behavior and messages could be improved by making them appropriate to the usage context.
For example, if the app knows it is connected, then it could offer to sync after you finish a review rather than only having a manual sync. I think it would only be in very rare cases that you do not want to sync your earlier changes.
If the app detects no internet connection, then words like 'unexpectedly failed' could be changed to something more intelligent such as 'requires internet connection'

**Comment by brianrak** [comment]
Hello, @issekinichou. Thanks for the feedback!

The app can indeed tell if there is an internet connection available, and we do use this throughout the app to make decisions on whether to do things. 

I can see that part of this question relates to #61 and the question on how and when user data is sync'd. To reiterate, for the most part, there is no need to use the Synchronize screen manually. The app will sync your changes in the background, continuously. If no connection is available, accumulated changes will be sync'd at the next opportunity. 

I'll see about improving the messaging around this.
