### ISSUE TITLE
When offline (no wifi), app welcome screen progress says "Finished sync successfully" but it does not sync at all.

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#60]
**Describe the bug**
When the app is working in offline mode, with no wifi connection, if you re-open it after some time, or quit and immediately relaunch, you get the splash screen and then welcome screen. The progress indicator says "Finished sync successfully". This is untrue since the app cannot sync.

The same message appears when you select menu item Synchronize while offline. It exits the current page to welcome screen and says "Finished sync successfully".

**To Reproduce**
Sign in
Disable wifi
Double tap home button and swipe up on app.
Tap home button
Open app
----
On any page while signed in but offline, select menu item Synchronize.

**Expected behavior**
The info should say something truthful, such as "Unable to sync" or "No internet connection" or "Working in offline mode"

**Smartphone (please complete the following information):**
 iPod touch 6
iOS 11.4.1

**Additional context**

**Comment by brianrak** [comment]
In 0.915, we have improved the messaging here to make it clear when the app is working in offline mode.
