### ISSUE TITLE
Bad line length word wrap in some text boxes in articles with dialogs on small-screen device in portrait mode. SEE ISSUE 63

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#62]
**Describe the bug**

UPDATE. Should have checked the website first. There is a problem there, which carries over to the app. See issue 63.

In articles involving dialogs, in portrait mode on a small-screen device, some text boxes have bad line length word wraps.
I have found this in many different articles, 
in both left and right side text boxes, 
mainly in long texts but some even longer ones are fine. 
For example in hotels 2 No reservations, the third blue box is cut off, but the fourth blue box, which is longer, is fine.
Rotate to landscape and same dialog text box no problem.

This issue affect both original articles and context linked from review card.

You may have trouble reproducing this if you don't have a small screen.
Let me know if you need me to test further or provide more screenshots.
iPod width is 640 pixels
On my iPad, same dialogs, no problem
wifi on or off has no effect.

**To Reproduce**
Use a small-screen device in portrait mode. Mine has a screen width of 640 pixels.
Open an article with dialogs. 
I tested airports, hotels. Problem occurs with several reproducibly. 
Streetside Tomomi part 1 just loses the face image in third yellow box.
Streetside Chiharu part 1 bad wrap in 4th yellow box text falls off screen.
Streetside Chiharu part 2 bad wrap in 1st yellow.
Trains aboard bullet train 6th yellow.

**Expected behavior**
Text box should be smaller and display all the text as in other properly displayed boxes

**Screenshots**
1. hotels 1 Checking in.
2. airports parent and child 1.

![unadjustednonraw_thumb_2e9a](https://user-images.githubusercontent.com/42171096/44651539-9b1e7380-a9e1-11e8-82b7-a4a68b56fec6.jpg)

![unadjustednonraw_thumb_2e8d](https://user-images.githubusercontent.com/42171096/44652048-d2d9eb00-a9e2-11e8-833d-502262f8f1a6.jpg)

**Smartphone (please complete the following information):**
 iPod touch 6
iOS 11.4.1

**Additional context**

**Comment by issekinichou** [comment]
Ha! Should have checked web site first.
Same issue there too.

**Comment by brianrak** [comment]
Website now fixed. App fixed in build 0.915.
