### ISSUE TITLE
Issue 62 is caused by web site bug

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#63]
**Describe the bug**
Issue 62 bug occurs on website too. See screenshots from safari on iPod.
On web site, the problem text fits in the the other text is indented. In the app, it's shifted to the right.

**To Reproduce**
Web site in safari on small screen device.
View article.

**Expected behavior**
Text boxes should all align vertically

**Screenshots**

![unadjustednonraw_thumb_2e9b](https://user-images.githubusercontent.com/42171096/44678257-ec555400-aa2f-11e8-87cb-8d4ab713323c.jpg)

![unadjustednonraw_thumb_2e9e](https://user-images.githubusercontent.com/42171096/44678270-f5462580-aa2f-11e8-9fc4-c055bc90880f.jpg)

![unadjustednonraw_thumb_2e9d](https://user-images.githubusercontent.com/42171096/44678303-fe36f700-aa2f-11e8-9224-1ce151217518.jpg)

![unadjustednonraw_thumb_2e9c](https://user-images.githubusercontent.com/42171096/44678321-04c56e80-aa30-11e8-8660-6df37448d77d.jpg)

**Smartphone (please complete the following information):**
 iPod touch 6
iOS 11.4.1

**Additional context**
Out of time tonight. Let me know if you need more from me on this.

**Comment by brianrak** [comment]
Now fixed on website. App fixed in build 0.915.

Please note that you will need to delete and recreate affected cards. My apologies for the inconvenience. Thanks for the great bug!
