### ISSUE TITLE
Announcement: Release Candidate 3 is now available.

### ISSUE THREAD

**Issue by brianrak** [brianrak/satori-reader-mobile-beta#65]
**UPDATE:** The build is now available for both Android and iOS.

---

Okay, everyone. We are getting close. Build 1.0.2 is available on both platforms. It contains mostly small, fit-and-finish fixes, along with two larger changes:

- Viewing an article now results in the downloading and caching of both the content and the audio. Previously it was just the content, if your download settings were set to Cloud. This meant that if you were in airplane mode, there was a chance you could view an article where the text content was available but not the data. Not cool. Now, the act of viewing an article guarantees that it will be available for you offline.

- A new user now gets a welcome banner that explains how the app works. (We had removed the full Welcome Tour shown on the website because we felt it was a little clunky for small devices.)

Please put this build through its paces. Thank you for all your help in making Satori Reader great!

**Comment by issekinichou** [comment]
Nothing new on Testflight (iOS ) yet. Does it normally take this long?
Has anyone else on iOS seen it yet?

Nice catch re airplane mode. After reading the above, I checked that on 1.0.1 and indeed the error messages are not cool.

**Comment by brianrak** [comment]
Hello, @issekinichou. I guess I was a little too quick on the draw with the announcement. Each build, even beta builds, have to be submitted to Apple for review. Usually, the reviews for the beta builds have been instant, but the last couple builds have taken a bit longer. The current build shows as still Waiting for Review. I'll update the main post to head off confusion in others.
