### ISSUE TITLE
Sign-up flow not ideal

### ISSUE THREAD

**Issue by zantoku** [brianrak/satori-reader-mobile-beta#69]
**Describe the bug**
When signing up for an account, after submitting the form, the "Sign up" button remains available. Pressing it again displays an error: "Error: An account with that email address already exists".
The only other available button is "Cancel".

**To Reproduce**
1. Open the app (not logged in).
2. Click on 'Create new account'
3. Fill out form and submit it.

**Expected behavior**
An opportunity to log in should be presented.  Alternatively, a button labeled other than "Cancel" (which suggests the account creation should be aborted), for example "Back", or "Done", should be presented.

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 12.0

**Comment by brianrak** [comment]
Hello, @zantoku. Thank you for the bug report! That's a great point. We'll be sure this gets improved in our next update.

**Comment by brianrak** [comment]
Fixed as of 1.0.7. Thank you!
