### ISSUE TITLE
Review card context sentences are original snapshots not latest corrections

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#79]
Context sentence in a review card may contain a mistake that has subsequently been corrected

**To Reproduce**
Study a review card with a context sentence that has been changed since the card was added.

**Expected behavior**
Context sentence should be the latest version, same as browser, but the app uses some snapshotting to cut down on data volume.

**Screenshots**
Split screen: browser left, app right.
![img_2190](https://user-images.githubusercontent.com/42171096/50779725-f9fdce80-1298-11e9-93a5-e3b109419c67.png)

**Smartphone (please complete the following information):**
 - iPad mini 4
iOS 12.1
satori beta 1.0.7

**Additional context**
As discussed in River Sanzu Aftermath and emails Jan 7th 2019.

**Comment by brianrak** [comment]
@issekinichou, this should be fixed in 1.1.0. Please let me know if it still repros for you.
