### ISSUE TITLE
Specific review card unable to render note boxes in context sentence popup

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#80]
**Describe the bug**
As screenshot. Card for hifu, popup for hiyakedome: unable too render.

**Expected behavior**
Should render boxes. Other card popups do ok.

**Screenshots**
![img_2191](https://user-images.githubusercontent.com/42171096/50974097-5869bd80-14e2-11e9-9bf0-396773c57279.PNG)

**Smartphone (please complete the following information):**
iPad mini 4
iOS 12.1
satori beta 1.0.7 beta

**Additional context**
As emailed 2019-01-10.

**Comment by brianrak** [comment]
Confirmed fixed in 1.1.0.
