### ISSUE TITLE
Specific EJ review card shows answer instead of ellipsis

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#81]
**Describe the bug**
As screenshot, EJ card for sorou shows the answer.

**Expected behavior**
Answer should be replaced by ellipsis, as is usual

**Screenshots**
![img_2194](https://user-images.githubusercontent.com/42171096/50974704-bb0f8900-14e3-11e9-8311-bac35bec1a7e.png)

**Smartphone (please complete the following information):**
 - iPad mini 4
iOS 12.1
satori beta 1.0.7

**Additional context**
I don't export EJ, but searching my JE export all list, I found two cards for 揃う
1. created 2016-04-14 next due 2019-08-29. 12-0
2. created 2018-04-20 next due 2019-04-06. 7-0
Both have two contexts, as screenshot. 
Why are there 2 cards?
The score is surprising. I only know it in context. In my flashcard app, which shows the kanji only, I have got it wrong.
I think I deleted the EJ card after taking screenshot. Anyway, I wouldn't see it for a long time.
Didn't tap Miss this time to keep it nearby, sorry.

**Comment by brianrak** [comment]
No repro as of build 1.1.0. I think this was probably fixed by changes in the way we synchronize article-sentence data for review cards (we no longer use potentially out-of-date snapshots).
