### ISSUE TITLE
App feels slower (March 2019) with recent synchronization enhancements

### ISSUE THREAD

**Issue by bengaskin** [brianrak/satori-reader-mobile-beta#84]
I'm sure this will be subjective, so I don't know that it warrants bug status, but...
The app certainly feels slower since the recent March 2019 sync efficiency updates.. I'm tempted to reinstall an older version of the apk that I've got saved.

My phone is not ancient by some standards, but not new.
Lollipop. Samsung Galaxy S6 Edge.

I'm OK in principle with the app occasionally starting slow if it's faster the next time.
But what is occasionally? For me seems multiple times per day.

After clearing my android cache today, checking I have over 7GB free storage space free (I know my phone gets slow if storage space is under 6GB)..

Close all apps.
Open Satori Reader. 
Wait for the app to start, say "finished sync successfully" and fully close the splash screen into the app itself...
I waited 1 minute 40 seconds.

Straightaway, test again. Click show-all-open apps button. Click close all apps
Wait 1.37
And again,
Wait 1.32

Other apps.
Gmail
4s
4s
4s

Facebook Slim
6s
4s

chrome
8s
7s

redditIsFun
9s
5s

Netflix
9s
5s

Do I have more review cards than other users you've tested with? Do other test users have lightning fast phones?

Could you please investigate, or give an in-app option for type-a sync vs type-b sync?

FWIW, I have "download all content" checked. I've read a lot of articles and saved a lot of review cards and contexts.

**Comment by bengaskin** [comment]
I guess I might as well close this, fixed by full uninstall and reinstall.

**Comment by brianrak** [comment]
Hello, @bengaskin. I know you closed this bug, but I just want to get a little more information. So it took 1:32 *after* a sync had just completed? That is definitely unexpected. I'm glad a complete reinstall fixed the issue, but I'd really like to know what was going on!

How fast do syncs go for you now?

**Comment by brianrak** [comment]
I made another improvement to sync in our latest update (1.2.2, going out today) that brought a certain part of syncs down by a factor of 50x for some users. I'm closing this bug for now, but please do let us know if you have any more trouble in this regard.
